version: 0.2

phases:
  post_build:
    commands:
      - mvn package
      - mv /codebuild/output/src397178900/ ./
artifacts:
  files:
    - /codebuild/output/src397178900/src/**/*
 discard-paths: yes
